apiVersion: v1
kind: Pod
metadata:
  labels:
    type: job
    job: slipway-jenkins

spec:
  containers:
    - name: python
      image: python:3
      tty: true
      command:
      - sleep
      - 1d
      # needed for creating containers from the tests
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: "800m"
          memory: "600Mi"
